
	{	displayID: "1",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_bananas",
	location3: "2_apples",
	location4: "3_oranges",
	location5: "1_apple",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyAllSusanBananas",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "3_bananas",
	target_figure3: "boy",
	object3: "bananas",
	instruction3: "Click on the boy that has all of Susan's bananas
"
},
{	displayID: "2",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "3_apples",
	location2: "2_oranges",
	location3: "2_bananas",
	location4: "3_pears",
	location5: "1_banana",
	location6: "1_orange",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyAllSusanApples",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "3_apples",
	target_figure3: "boy",
	object3: "apples",
	instruction3: "Click on the boy that has all of Susan's apples
"
},
{	displayID: "3",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_apples",
	location2: "3_pears",
	location3: "2_bananas",
	location4: "3_oranges",
	location5: "1_apple",
	location6: "1_banana",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyTwoSusanApples",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "2_apples",
	target_figure3: "boy",
	object3: "apples",
	instruction3: "Click on the boy that has two of Susan's apples
"
},
{	displayID: "4",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_apples",
	location3: "3_bananas",
	location4: "2_oranges",
	location5: "1_orange",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlThreeSusanBananas",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "3_bananas",
	target_figure3: "girl",
	object3: "bananas",
	instruction3: "Click on the girl that has three of Susan's bananas
"
},
{	displayID: "5",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_apples",
	location3: "3_oranges",
	location4: "2_bananas",
	location5: "1_banana",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeSusanBananas",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "2_bananas",
	target_figure3: "girl",
	object3: "bananas",
	instruction3: "Click on the girl that has some of Susan's bananas
"
},
{	displayID: "6",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_oranges",
	location2: "3_bananas",
	location3: "2_apples",
	location4: "3_pears",
	location5: "1_apple",
	location6: "1_orange",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeSusanApples",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "2_apples",
	target_figure3: "girl",
	object3: "apples",
	instruction3: "Click on the girl that has some of Susan's apples
"
},
{	displayID: "7",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "3_scissors",
	location2: "2_pencils",
	location3: "3_erasers",
	location4: "2_rulers",
	location5: "1_pencil",
	location6: "1_ruler",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyTwoMichaelPencils",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "2_pencils",
	target_figure3: "boy",
	object3: "pencils",
	instruction3: "Click on the boy that has two of Michael's pencils
"
},
{	displayID: "8",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "2_scissors",
	location2: "3_pencils",
	location3: "2_erasers",
	location4: "3_rulers",
	location5: "1_eraser",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlThreeMichaelRulers",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "3_rulers",
	target_figure3: "girl",
	object3: "rulers",
	instruction3: "Click on the girl that has three of Michael's rulers
"
},
{	displayID: "9",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "3_pencils",
	location2: "2_scissors",
	location3: "2_rulers",
	location4: "3_erasers",
	location5: "1_ruler",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeMichaelRulers",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "2_rulers",
	target_figure3: "girl",
	object3: "rulers",
	instruction3: "Click on the girl that has some of Michael's rulers
"
},
{	displayID: "10",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "3_rulers",
	location2: "2_erasers",
	location3: "3_scissors",
	location4: "2_pencils",
	location5: "1_pencil",
	location6: "1_eraser",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeMichaelPencils",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "2_pencils",
	target_figure3: "girl",
	object3: "pencils",
	instruction3: "Click on the girl that has some of Michael's pencils
"
},
{	displayID: "11",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "2_erasers",
	location2: "3_pencils",
	location3: "2_rulers",
	location4: "3_scissors",
	location5: "1_ruler",
	location6: "1_eraser",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyAllMichaelPencils",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "3_pencils",
	target_figure3: "boy",
	object3: "pencils",
	instruction3: "Click on the boy that has all of Michael's pencils
"
},
{	displayID: "12",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "3_rulers",
	location2: "2_scissors",
	location3: "2_pencils",
	location4: "3_erasers",
	location5: "1_pencil",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyAllMichaelRulers",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "3_rulers",
	target_figure3: "boy",
	object3: "rulers",
	instruction3: "Click on the boy that has all of Michael's rulers
"
},
{	displayID: "13",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "2_knives",
	location2: "3_spoons",
	location3: "3_plates",
	location4: "2_forks",
	location5: "1_fork",
	location6: "1_knife",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeAmyForks",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "2_forks",
	target_figure3: "girl",
	object3: "forks",
	instruction3: "Click on the girl that has some of Amy's forks
"
},
{	displayID: "14",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "2_spoons",
	location2: "3_knives",
	location3: "2_plates",
	location4: "3_forks",
	location5: "1_spoon",
	location6: "1_plate",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeAmySpoons",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "2_spoons",
	target_figure3: "boy",
	object3: "spoons",
	instruction3: "Click on the boy that has some of Amy's spoons
"
},
{	displayID: "15",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "2_spoons",
	location2: "3_plates",
	location3: "2_knives",
	location4: "3_forks",
	location5: "1_spoon",
	location6: "1_knife",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllAmyForks",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "3_forks",
	target_figure3: "girl",
	object3: "forks",
	instruction3: "Click on the girl that has all of Amy's forks
"
},
{	displayID: "16",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "2_forks",
	location2: "3_knives",
	location3: "3_spoons",
	location4: "2_plates",
	location5: "1_fork",
	location6: "1_plate",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllAmySpoons",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "3_spoons",
	target_figure3: "girl",
	object3: "spoons",
	instruction3: "Click on the girl that has all of Amy's spoons
"
},
{	displayID: "17",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "2_spoons",
	location2: "3_forks",
	location3: "2_knives",
	location4: "3_plates",
	location5: "1_spoon",
	location6: "1_knife",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyTwoAmySpoons",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "2_spoons",
	target_figure3: "boy",
	object3: "spoons",
	instruction3: "Click on the boy that has two of Amy's spoons
"
},
{	displayID: "18",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "3_knives",
	location2: "2_plates",
	location3: "3_spoons",
	location4: "2_forks",
	location5: "1_plate",
	location6: "1_fork",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyThreeAmyKnives",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "3_knives",
	target_figure3: "boy",
	object3: "knives",
	instruction3: "Click on the boy that has three of Amy's knives
"
},
{	displayID: "19",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "3_oranges",
	location2: "2_apples",
	location3: "2_pears",
	location4: "3_bananas",
	location5: "1_banana",
	location6: "1_orange",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllSusanPears",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "all",
	determiner: "all",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "2_pears",
	target_figure3: "girl",
	object3: "pears",
	instruction3: "Click on the girl that has all of Susan's pears
"
},
{	displayID: "20",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "3_pears",
	location2: "2_bananas",
	location3: "3_apples",
	location4: "2_oranges",
	location5: "1_apple",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllSusanOranges",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "all",
	determiner: "all",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "2_oranges",
	target_figure3: "girl",
	object3: "oranges",
	instruction3: "Click on the girl that has all of Susan's oranges
"
},
{	displayID: "21",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "3_bananas",
	location2: "2_oranges",
	location3: "3_apples",
	location4: "2_pears",
	location5: "1_apple",
	location6: "1_banana",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyTwoSusanOranges",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "2_oranges",
	target_figure3: "boy",
	object3: "oranges",
	instruction3: "Click on the boy that has two of Susan's oranges
"
},
{	displayID: "22",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "2_apples",
	location2: "3_pears",
	location3: "3_oranges",
	location4: "2_bananas",
	location5: "1_orange",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyThreeSusanPears",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "3_pears",
	target_figure3: "boy",
	object3: "pears",
	instruction3: "Click on the boy that has three of Susan's pears
"
},
{	displayID: "23",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "3_apples",
	location2: "2_pears",
	location3: "3_oranges",
	location4: "2_bananas",
	location5: "1_apple",
	location6: "1_orange",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeSusanOranges",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "some",
	determiner: "some",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "3_oranges",
	target_figure3: "girl",
	object3: "oranges",
	instruction3: "Click on the girl that has some of Susan's oranges
"
},
{	displayID: "24",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "2_apples",
	location2: "3_pears",
	location3: "3_bananas",
	location4: "2_oranges",
	location5: "1_banana",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeSusanPears",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "some",
	determiner: "some",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "3_pears",
	target_figure3: "boy",
	object3: "pears",
	instruction3: "Click on the boy that has some of Susan's pears
"
},
{	displayID: "25",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "3_erasers",
	location2: "2_rulers",
	location3: "3_scissors",
	location4: "2_pencils",
	location5: "1_eraser",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlThreeMichaelScissors",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "3_scissors",
	target_figure3: "girl",
	object3: "scissors",
	instruction3: "Click on the girl that has three of Michael's scissors
"
},
{	displayID: "26",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "3_pencils",
	location2: "2_scissors",
	location3: "2_erasers",
	location4: "3_rulers",
	location5: "1_pencil",
	location6: "1_ruler",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlTwoMichaelErasers",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "2_erasers",
	target_figure3: "girl",
	object3: "erasers",
	instruction3: "Click on the girl that has two of Michael's erasers
"
},
{	displayID: "27",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "2_rulers",
	location2: "3_erasers",
	location3: "2_scissors",
	location4: "3_pencils",
	location5: "1_pencil",
	location6: "1_eraser",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeMichaelErasers",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "some",
	determiner: "some",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "3_erasers",
	target_figure3: "boy",
	object3: "erasers",
	instruction3: "Click on the boy that has some of Michael's erasers
"
},
{	displayID: "28",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "3_scissors",
	location2: "2_pencils",
	location3: "2_erasers",
	location4: "3_rulers",
	location5: "1_ruler",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeMichaelScissors",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "some",
	determiner: "some",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "3_scissors",
	target_figure3: "boy",
	object3: "scissors",
	instruction3: "Click on the boy that has some of Michael's scissors
"
},
{	displayID: "29",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "3_pencils",
	location2: "2_erasers",
	location3: "3_scissors",
	location4: "2_rulers",
	location5: "1_pencil",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyAllMichaelErasers",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "all",
	determiner: "all",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "2_erasers",
	target_figure3: "boy",
	object3: "erasers",
	instruction3: "Click on the boy that has all of Michael's erasers
"
},
{	displayID: "30",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "3_erasers",
	location2: "2_pencils",
	location3: "2_scissors",
	location4: "3_rulers",
	location5: "1_ruler",
	location6: "1_eraser",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllMichaelScissors",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "all",
	determiner: "all",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "2_scissors",
	target_figure3: "girl",
	object3: "scissors",
	instruction3: "Click on the girl that has all of Michael's scissors
"
},
{	displayID: "31",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "3_plates",
	location2: "2_forks",
	location3: "3_spoons",
	location4: "2_knives",
	location5: "1_spoon",
	location6: "1_plate",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeAmyPlates",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "some",
	determiner: "some",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "3_plates",
	target_figure3: "boy",
	object3: "plates",
	instruction3: "Click on the boy that has some of Amy's plates
"
},
{	displayID: "32",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "2_spoons",
	location2: "3_knives",
	location3: "3_forks",
	location4: "2_plates",
	location5: "1_fork",
	location6: "1_knife",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeAmyKnives",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "some",
	determiner: "some",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "3_knives",
	target_figure3: "boy",
	object3: "knives",
	instruction3: "Click on the boy that has some of Amy's knives
"
},
{	displayID: "33",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "2_plates",
	location2: "3_spoons",
	location3: "2_forks",
	location4: "3_knives",
	location5: "1_spoon",
	location6: "1_knife",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyAllAmyPlates",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "all",
	determiner: "all",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "2_plates",
	target_figure3: "boy",
	object3: "plates",
	instruction3: "Click on the boy that has all of Amy's plates
"
},
{	displayID: "34",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "2_spoons",
	location2: "3_plates",
	location3: "3_forks",
	location4: "2_knives",
	location5: "1_fork",
	location6: "1_plate",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllAmyKnives",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "all",
	determiner: "all",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "2_knives",
	target_figure3: "girl",
	object3: "knives",
	instruction3: "Click on the girl that has all of Amy's knives
"
},
{	displayID: "35",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "3_spoons",
	location2: "2_forks",
	location3: "3_knives",
	location4: "2_plates",
	location5: "1_spoon",
	location6: "1_knife",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlTwoAmyPlates",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "2_plates",
	target_figure3: "girl",
	object3: "plates",
	instruction3: "Click on the girl that has two of Amy's plates
"
},
{	displayID: "36",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "3_plates",
	location2: "2_knives",
	location3: "2_spoons",
	location4: "3_forks",
	location5: "1_plate",
	location6: "1_fork",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlThreeAmyForks",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "3_forks",
	target_figure3: "girl",
	object3: "forks",
	instruction3: "Click on the girl that has three of Amy's forks
"
},
{	displayID: "37",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "1_apple",
	location2: "3_pears",
	location3: "3_bananas",
	location4: "3_oranges",
	location5: "2_apples",
	location6: "0",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyOneSusanApples",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "one",
	determiner: "one",
	size: "small",
	ExpFiller: "Filler",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "1_apple",
	target_figure3: "boy",
	object3: "apples",
	instruction3: "Click on the boy that has one of Susan's apples
"
},
{	displayID: "38",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "1_plate",
	location2: "3_knives",
	location3: "3_forks",
	location4: "3_spoons",
	location5: "2_plates",
	location6: "0",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyOneAmyPlates",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "one",
	determiner: "one",
	size: "small",
	ExpFiller: "Filler",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "1_plate",
	target_figure3: "boy",
	object3: "plates",
	instruction3: "Click on the boy that has one of Amy's plates
"
},
{	displayID: "39",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "33-33",
	location1: "3_forks",
	location2: "1_spoon",
	location3: "3_plates",
	location4: "3_knives",
	location5: "2_spoons",
	location6: "0",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyOneAmySpoons",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "one",
	determiner: "one",
	size: "small",
	ExpFiller: "Filler",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "1_spoon",
	target_figure3: "boy",
	object3: "spoons",
	instruction3: "Click on the boy that has one of Amy's spoons
"
},
{	displayID: "40",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "3_erasers",
	location2: "1_ruler",
	location3: "3_pencils",
	location4: "3_scissors",
	location5: "2_scissors",
	location6: "0",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyOneMichaelRulers",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "one",
	determiner: "one",
	size: "small",
	ExpFiller: "Filler",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "1_ruler",
	target_figure3: "boy",
	object3: "rulers",
	instruction3: "Click on the boy that has one of Michael's rulers
"
},
{	displayID: "41",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "33-33",
	location1: "3_pencils",
	location2: "3_scissors",
	location3: "1_eraser",
	location4: "3_rulers",
	location5: "2_erasers",
	location6: "0",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlOneMichaelErasers",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "one",
	determiner: "one",
	size: "small",
	ExpFiller: "Filler",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "1_eraser",
	target_figure3: "girl",
	object3: "erasers",
	instruction3: "Click on the girl that has one of Michael's erasers
"
},
{	displayID: "42",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "3_bananas",
	location2: "3_oranges",
	location3: "3_apples",
	location4: "1_pear",
	location5: "2_pears",
	location6: "0",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlOneSusanPears",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "one",
	determiner: "one",
	size: "small",
	ExpFiller: "Filler",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "1_pear",
	target_figure3: "girl",
	object3: "pears",
	instruction3: "Click on the girl that has one of Susan's pears
"
},
{	displayID: "43",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "4_scissors",
	location2: "1_pencil",
	location3: "2_rulers",
	location4: "3_erasers",
	location5: "1_pencil",
	location6: "1_eraser",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyFourMichaelScissors",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "four",
	determiner: "four",
	size: "big",
	ExpFiller: "Filler",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "2",
	target_object3: "4_scissors",
	target_figure3: "boy",
	object3: "scissors",
	instruction3: "Click on the boy that has four of Michael's scissors
"
},
{	displayID: "44",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "1_orange",
	location2: "4_bananas",
	location3: "3_pears",
	location4: "2_apples",
	location5: "1_orange",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyFourSusanBananas",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "four",
	determiner: "four",
	size: "big",
	ExpFiller: "Filler",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "2",
	target_object3: "4_bananas",
	target_figure3: "boy",
	object3: "bananas",
	instruction3: "Click on the boy that has four of Susan's bananas
"
},
{	displayID: "45",
	setting: "fruit",
	figure: "Susan's",
	display_type: "44-22",
	location1: "2_pears",
	location2: "3_apples",
	location3: "4_oranges",
	location4: "1_banana",
	location5: "1_banana",
	location6: "1_apple",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlFourSusanOranges",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "four",
	determiner: "four",
	size: "big",
	ExpFiller: "Filler",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "4_oranges",
	target_figure3: "girl",
	object3: "oranges",
	instruction3: "Click on the girl that has four of Susan's oranges
"
},
{	displayID: "46",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "1_spoon",
	location2: "3_plates",
	location3: "4_knives",
	location4: "2_forks",
	location5: "1_spoon",
	location6: "1_plate",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlFourAmyKnives",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "four",
	determiner: "four",
	size: "big",
	ExpFiller: "Filler",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "2",
	target_object3: "4_knives",
	target_figure3: "girl",
	object3: "knives",
	instruction3: "Click on the girl that has four of Amy's knives
"
},
{	displayID: "47",
	setting: "kitchenwares",
	figure: "Amy's",
	display_type: "44-22",
	location1: "1_knife",
	location2: "3_forks",
	location3: "2_spoons",
	location4: "4_plates",
	location5: "1_knife",
	location6: "1_fork",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlFourAmyPlates",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "four",
	determiner: "four",
	size: "big",
	ExpFiller: "Filler",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "4_plates",
	target_figure3: "girl",
	object3: "plates",
	instruction3: "Click on the girl that has four of Amy's plates
"
},
{	displayID: "48",
	setting: "stationeries",
	figure: "Michael's",
	display_type: "44-22",
	location1: "1_ruler",
	location2: "2_erasers",
	location3: "3_scissors",
	location4: "4_pencils",
	location5: "1_ruler",
	location6: "1_scissor",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlFourMichaelPencils",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "four",
	determiner: "four",
	size: "big",
	ExpFiller: "Filler",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "2",
	target_object3: "4_pencils",
	target_figure3: "girl",
	object3: "pencils",
	instruction3: "Click on the girl that has four of Michael's pencils
"
},
{	displayID: "",
	