{	displayID: "1",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_bananas",
	location3: "2_apples",
	location4: "3_oranges",
	location5: "1_apple",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeSusanPears",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "1",
	target_object3: "2_pears",
	target_figure3: "boy",
	object3: "pears",
	instruction3: "Click on the boy that has some of Susan's pears"
},
{	displayID: "2",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "3_apples",
	location2: "2_oranges",
	location3: "2_bananas",
	location4: "3_pears",
	location5: "1_banana",
	location6: "1_orange",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeSusanOranges",
	target1: "2",
	target2: "8",
	competitor1: "1",
	competitor2: "7",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI2",
	correctAns2: "AOI8",
	list: "1",
	target_object3: "2_oranges",
	target_figure3: "boy",
	object3: "oranges",
	instruction3: "Click on the boy that has some of Susan's oranges"
},
