{	displayID: "1",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_bananas",
	location3: "2_apples",
	location4: "3_oranges",
	location5: "1_apple",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyTwoSusanPears",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "num",
	determiner: "two",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "3",
	target_object3: "2_pears",
	target_figure3: "boy",
	object3: "pears",
	instruction3: "Click on the boy that has two of Susan's pears"
},
{	displayID: "2",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "3_apples",
	location2: "2_oranges",
	location3: "2_bananas",
	location4: "3_pears",
	location5: "1_banana",
	location6: "1_orange",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoyThreeSusanApples",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "num",
	determiner: "three",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "3",
	target_object3: "3_apples",
	target_figure3: "boy",
	object3: "apples",
	instruction3: "Click on the boy that has three of Susan's apples"
},
{	displayID: "3",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_apples",
	location2: "3_pears",
	location3: "2_bananas",
	location4: "3_oranges",
	location5: "1_apple",
	location6: "1_banana",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "BoySomeSusanApples",
	target1: "1",
	target2: "7",
	competitor1: "2",
	competitor2: "8",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI1",
	correctAns2: "AOI7",
	list: "3",
	target_object3: "2_apples",
	target_figure3: "boy",
	object3: "apples",
	instruction3: "Click on the boy that has some of Susan's apples"
},
{	displayID: "4",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_apples",
	location3: "3_bananas",
	location4: "2_oranges",
	location5: "1_orange",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlSomeSusanOranges",
	target1: "4",
	target2: "10",
	competitor1: "3",
	competitor2: "9",
	condition: "some",
	determiner: "some",
	size: "small",
	ExpFiller: "Exp",
	correctAns1: "AOI4",
	correctAns2: "AOI10",
	list: "3",
	target_object3: "2_oranges",
	target_figure3: "girl",
	object3: "oranges",
	instruction3: "Click on the girl that has some of Susan's oranges"
},
{	displayID: "5",
	setting: "fruit",
	figure: "Susan's",
	display_type: "33-33",
	location1: "2_pears",
	location2: "3_apples",
	location3: "3_oranges",
	location4: "2_bananas",
	location5: "1_banana",
	location6: "1_pear",
	location7: "boy",
	location8: "boy",
	location9: "girl",
	location10: "girl",
	Prime: "GirlAllSusanOranges",
	target1: "3",
	target2: "9",
	competitor1: "4",
	competitor2: "10",
	condition: "all",
	determiner: "all",
	size: "big",
	ExpFiller: "Exp",
	correctAns1: "AOI3",
	correctAns2: "AOI9",
	list: "3",
	target_object3: "3_oranges",
	target_figure3: "girl",
	object3: "oranges",
	instruction3: "Click on the girl that has all of Susan's oranges"
},
{	displayID: "",
	